### ISSUE TITLE
Creative Assignment 1

### ISSUE THREAD

**Issue by zoeiacovino** [VIS-2129-F2020/ziacovino-vis#1]
https://vis-2129-f2020.github.io/ziacovino-vis/Creative-Assignment-1.html

**Comment by bauranov** [comment]
Really good work! Everything looks great, You can format your titles as headers by adding # at the beginning of the row. See more here https://www.markdownguide.org/basic-syntax/.

Make sure to assign me to the issue, too.
Keep up the good work.
