### ISSUE TITLE
Scale Problem

### ISSUE THREAD

**Issue by zoeiacovino** [VIS-2129-F2020/ziacovino-vis#3]
https://github.com/VIS-2129-F2020/ziacovino-vis/blob/master/Creative-Assignment-3.html

**Comment by zoeiacovino** [comment]
Apologies, here is the right file: https://github.com/VIS-2129-F2020/ziacovino-vis/blob/master/Creative%20Assignment%203.Rmd

**Comment by c-voulgaris** [comment]
It could be that your x,y coordinates are just in a weird coordinate system. Try reading in the data as lat/lon coordinates. If you do that, you'd need to set the CRS in `st_as_sf()` to a coordinate system that uses lat/lon values (I suggest "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"). Then, once you've read it in with lat/lon coordinates, you can transform it to state plane (which you're already doing in lines 49 and 50).

This should work: 

Add `lat_lon_CRS <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"` to line 29.

Then replace line 32 with

```
accidents <- st_as_sf(read.csv("Vision_Zero_Crash_Records.csv"), 
                      coords = c("long", "lat"), 
                      crs= lat_lon_CRS) 
```

And uncomment (remove the #s) from lines 49 and 50. 

That should fix it.
