### ISSUE TITLE
Joining

### ISSUE THREAD

**Issue by c-voulgaris** [VIS-2129-F2020/ziacovino-vis#4]
Also, some separate issues that I see as I'm looking through your code (which I think are just modifications to the code you copy/pasted that you haven't gotten to yet because you were sorting out the initial issue).

On line 99: Your joined dataframe doesn't have a variable called Name.y, so you'll get an error when you run that line. Replace line 99 with `  mutate(by_ramps = !is.na(dispatch_ts.y))`

```
           label = paste("Of the ", 
                         prettyNum(n_accidents, big.mark = ","),
                         " accidents in Boston\n", 
                         prettyNum(n_ramps_accidents, big.mark = ","),
                         " (", 
                         prettyNum(100*pct_ramps_accidents, digits = 0),
                         "%) are within 10\nmeters of a pedestrian ramp.",
                         sep = ""),
```

**Comment by zoeiacovino** [comment]
The dispatch time stamp would work because they are unique values for each point right? When I tried it I got this error: 
 Error: cannot allocate vector of size 427.9 Mb

**Comment by c-voulgaris** [comment]
It doesn’t need to be a unique value for each point. It can be any variable that doesn’t have any NAs before the join. Did you close the issue because you got it working?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zoeiacovino** [comment]
I did yes! I just restarted R Studio, not sure why it worked but it did.
