### ISSUE TITLE
Creative Assignment 3

### ISSUE THREAD

**Issue by zoeiacovino** [VIS-2129-F2020/ziacovino-vis#5]
For grading: https://vis-2129-f2020.github.io/ziacovino-vis/Creative-Assignment-3.html

**Comment by bauranov** [comment]
Good work. Here are some comments:

- The thickness of borders in the first plot is overwhelming, makes it difficult to see other elements of the map. Not too informative, but aesthetically very pleasing. 
- In the fourth plot, the panel background color makes it impossible to read the map.
- Looks like you experimented with different colors, which is great, but make sure the plots are clear enough so they convey information. The last two plots, and especially the last one, are almost impossible to read.
