### ISSUE TITLE
iso_areas weirdness

### ISSUE THREAD

**Issue by zoeiacovino** [VIS-2129-F2020/ziacovino-vis#6]
https://github.com/VIS-2129-F2020/ziacovino-vis/blob/master/Creative%20Assignment%204.Rmd
In Line 89, I had to add a couple other arguments to get the code to run, which I think might have resulted in the 1s, 2s, and 3s, in my drive and walk variables.

**Comment by bauranov** [comment]
I'm sorry, is there a specific question?
Edit: I just saw the email. I'll look into it.

**Comment by zoeiacovino** [comment]
Thanks, yes I realized as I was sending the email some more context would be useful. Thank you!

**Comment by c-voulgaris** [comment]
This is a question that Zoe and I discussed briefly after class - the problem she's having is that in the dataframe she uses to create her scatter plot all of her area values are integers - either 1, 2, or 3. I have class from 3 to 6, so I won't be able to look at this until tomorrow at the earliest. Alex, if you have time to take a closer look today, that would be great.
________________________________

**Comment by bauranov** [comment]
In Line 89 you added values_fn = length which counts the number of elements in the *value* column (either 0 if it's NA, 1 if it's one number, or 2 if it's a list of two numbers). You have two options:
- Remove values_fn altogether, you will get iso_areas data frame with walk and drive columns that contain NA's, numbers and lists. Add this code after iso_areas and it should be fine
iso_areas <- iso_areas %>%
  filter(drive != "NULL", walk != "NULL") %>%
  filter(str_detect(drive,"c")==FALSE) 
- You can keep values_fn if you really like it, but change length to mean. This will return NA's, numbers and means of the lists. Then you will need to remove NA's with 
iso_areas <- iso_areas %>%
    filter(!is.na(drive), !is.na(walk))

**Comment by zoeiacovino** [comment]
Turning length to mean worked, without the values_fn I couldn't create variables for drive or walk in the iso_areas frame. Not sure why, but I am guessing its fine. Thanks!
