### ISSUE TITLE
Conditional Formatting Issue

### ISSUE THREAD

**Issue by zoeiacovino** [VIS-2129-F2020/ziacovino-vis#8]
https://github.com/VIS-2129-F2020/ziacovino-vis/blob/0b3ce9d3494e400670e62de6092547d3f4e0ab11/Creative%20Assignment%206.Rmd#L55

Hi Carole and Alex, 

Here is my CA6 code with the issue of conditional formatting not working correctly. My goal is to get each point to appear differently depending on the "mode_type" value. Carole didn't see what was stopping it immediately this morning. Sorry it took so long to the issue up! 
Thanks, Zoe

**Comment by bauranov** [comment]
Hi Zoe,
Leaflet has different logic than ggplot when it comes to dynamic colors. You need to create a colorFactor function, and then call that function in leaflet(). 

```{r}
color_bins <- colorFactor(rainbow(3), sb_accidents$mode_type)

street_risks <- leaflet(sb_accidents) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addCircles(fillColor = color_bins(sb_accidents$mode_type),  
             stroke = FALSE, radius = 20...
```
I covered this last Friday, here's a tutorial https://vis-2129-f2020.github.io/tutorials/Interactive_maps.html.

**Comment by zoeiacovino** [comment]
Thank you Alex!!
